swagger: '2.0'
info:
  title: "Mechanic API"
  description: "This is an API to access Service Tickets and Inventory for a Mechanic Shop"
  version: "1.0.0"
host: "127.0.0.1:5000"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"
paths: 
definitions: 